

const TOGGLE_TASK_COMPLETENESS = 'TOGGLE_TASK_COMPLETENESS';
const REORDER_TASKS = 'REORDER_TASKS';
const SET_LOADED_TASKS = 'SET_LOADED_TASKS';
const CLEAR_STATE = 'CLEAR_STATE';

export const tasksActionTypes = {
    REORDER_TASKS,
    TOGGLE_TASK_COMPLETENESS,
    SET_LOADED_TASKS,
    CLEAR_STATE
};